### PR TITLE
fix(core): restrict AVX2 normalize to x86_64 (fix i686 build)

### LINKED ISSUE #656: [Bug]: Build failing for x86 32 bit cpus
### Which fff frontend?

Other / multiple

### has logs

```
   Compiling socks v0.3.4
   Compiling hashlink v0.12.0
   Compiling is-docker v0.2.0
   Compiling toml_datetime v1.1.1+spec-1.1.0
   Compiling mio v0.8.11
   Compiling page_size v0.6.0
   Compiling typed-path v0.12.3
   Compiling symlink v0.1.0
   Compiling fff-search v0.9.6
   Compiling chrono-tz v0.10.4
   Compiling fallible-iterator v0.3.0
   Compiling arrayref v0.3.9
   Compiling constant_time_eq v0.4.2
   Compiling debug_unsafe v0.1.4
   Compiling unicode-id v0.3.6
   Compiling pathdiff v0.2.3
   Compiling fallible-streaming-iterator v0.1.9
   Compiling toml_writer v1.1.1+spec-1.1.0
   Compiling linux-raw-sys v0.4.15
   Compiling utf8-zero v0.8.1
   Compiling jiff v0.2.23
   Compiling ureq v3.3.0
   Compiling rusqlite v0.40.1
   Compiling parse_datetime v0.14.0
   Compiling zip v7.2.0
   Compiling markdown v1.0.0
   Compiling atoi_simd v0.17.0
   Compiling tracing-appender v0.2.5
   Compiling notify v6.1.1
   Compiling is-wsl v0.4.0
   Compiling ignore v0.4.25
   Compiling dirs v5.0.1
   Compiling phf v0.12.1
   Compiling nu-table v0.114.0 (/home/builder/.termux-build/nushell/src/crates/nu-table)
   Compiling pest_consume v1.1.3
   Compiling rand v0.9.2
   Compiling fff-notify-debouncer-full v0.9.4
   Compiling serde_urlencoded v0.7.1
   Compiling etcetera v0.10.0
   Compiling codepage v0.1.2
   Compiling quick-xml v0.39.4
   Compiling nuon v0.114.0 (/home/builder/.termux-build/nushell/src/crates/nuon)
   Compiling nu-heavy-utils v0.114.0 (/home/builder/.termux-build/nushell/src/crates/nu-heavy-utils)
   Compiling pori v0.0.0
   Compiling serde_spanned v1.1.1
   Compiling fff-grep v0.9.6
   Compiling fd-lock v4.0.4
   Compiling neo_frizbee v0.10.3
   Compiling serde_derive_internals v0.29.1
   Compiling itertools v0.13.0
   Compiling memmap2 v0.9.10
   Compiling platform-info v2.0.5
   Compiling csv-core v0.1.13
   Compiling glidesort v0.1.2
   Compiling openssl-probe v0.2.1
   Compiling is_debug v1.1.0
   Compiling atomic-waker v1.1.2
   Compiling fff-query-parser v0.9.6
   Compiling unsafe-libyaml v0.2.11
   Compiling fs_extra v1.3.0
   Compiling smol_str v0.3.6
   Compiling fast-float2 v0.2.3
   Compiling calamine v0.35.0
   Compiling shadow-rs v2.0.0
   Compiling git2 v0.20.4
   Compiling mq-markdown v0.6.0
   Compiling serde_yaml v0.9.34+deprecated
   Compiling uu_mv v0.9.0
   Compiling h2 v0.4.13
   Compiling rustls-native-certs v0.8.3
   Compiling reedline v0.49.0
error[E0432]: unresolved import `std::arch::x86_64`
   --> /home/builder/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/fff-search-0.9.6/src/bigram_filter.rs:626:20
    |
626 |     use std::arch::x86_64::*;
    |                    ^^^^^^ could not find `x86_64` in `arch`

   Compiling csv v1.4.0
   Compiling uu_uname v0.9.0
   Compiling schemars_derive v1.2.1
   Compiling toml v1.1.2+spec-1.1.0
For more information about this error, try `rustc --explain E0432`.
error: could not compile `fff-search` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `nu v0.114.0 (/home/builder/.termux-build/nushell/src)`, intermediate artifacts can be found at `/home/builder/.termux-build/nushell/src/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_BUILD_BUILD_DIR` to that path.
Error: Process completed with exit code 101.
```

### Description

Since https://github.com/dmtrKovalenko/fff/pull/566 the fff-search crate is failing to build for x86 32 bit CPUs (target: i686-unknown-linux-gnu). I believe this line is responsible for the issue, where the `x86_64` modules is imported even for 32 bit CPUs.
https://github.com/dmtrKovalenko/fff/blob/98af56c393a596292a24fb00d5b672306706b07c/crates/fff-core/src/bigram_filter.rs#L621-L627

### PR DESCRIPTION
**Pull request by gustav-fff**
Closes #656

## Root cause
`normalize_bytes` in `crates/fff-core/src/bigram_filter.rs` gated the AVX2 dispatch and the `normalize_bytes_avx2` fn on `#[cfg(any(target_arch = \"x86_64\", target_arch = \"x86\"))]`, but the body unconditionally does `use std::arch::x86_64::*;`. On 32-bit x86 (`i686-unknown-linux-gnu`) `std::arch::x86_64` does not exist, so `fff-search` failed to compile:

```
error[E0432]: unresolved import `std::arch::x86_64`
   --> fff-search-0.9.6/src/bigram_filter.rs:626:20
    |
626 |     use std::arch::x86_64::*;
    |                    ^^^^^^ could not find `x86_64` in `arch`
```

Regressed in #566. Reported by @Juhan280 hitting this while packaging nushell for termux i686 android devices.

## Fix
Restrict the AVX2 dispatch and the `normalize_bytes_avx2` implementation to `#[cfg(target_arch = \"x86_64\")]`. On 32-bit x86 we fall back to `normalize_bytes_scalar`, which LLVM auto-vectorises with the baseline SIMD anyway. Per maintainer + @fdncred: dropping SIMD on 32-bit x86 is acceptable — compiling at all is more important.

Also add a `Build i686-unknown-linux-gnu` CI job in `.github/workflows/rust.yml` so this regresses loudly next time. The job installs `gcc-multilib`, adds the `i686-unknown-linux-gnu` target, and runs `cargo build -p fff-search --target i686-unknown-linux-gnu`.

## Steps to reproduce
On pre-fix `main` (commit 8c76a1b):

```sh
rustup target add i686-unknown-linux-gnu
sudo apt-get install -y gcc-multilib   # linux host
cargo build -p fff-search --target i686-unknown-linux-gnu
```

Expected: build succeeds. Actual on pre-fix `main`: `error[E0432]: unresolved import 'std::arch::x86_64'` at `crates/fff-core/src/bigram_filter.rs:626`.

## How verified
- `cargo check -p fff-search --no-default-features --features ripgrep` on x86_64 macOS: clean.
- `cargo clippy -p fff-search --no-default-features --features ripgrep -- -D warnings`: clean.
- New CI job exercises the i686 build path on every PR; cross-compile toolchain not available locally on macOS host, so verification of the 32-bit target itself is deferred to CI.

Automated triage via Gustav. Honk-Honk 🪿

### CODE REVIEW

**Comment by dmtrKovalenko** [comment]
@gustav-fff iterate on this PR and guard all the non x86_64 code that is failing to compile

**Comment by gustav-fff** [comment]
[triage-bot] DIRECTED: already guarded, i686 CI green as of afc23c4.

Timeline: your comment at 17:55:06 UTC preceded commit afc23c4 (17:57:28 UTC), which silenced the unused `i1`/`i2` bindings in `select_rare_pair` that CI's `-D unused-variables` was rejecting on 32-bit x86. Latest run:

- `Build i686-unknown-linux-gnu`: pass (55s)
- `cargo clippy` (`-D warnings`): pass
- `cargo fmt`: pass

Grep swept for every arch-specific site in `crates/`:

- `crates/fff-core/src/bigram_filter.rs:596` — AVX2 dispatch `#[cfg(target_arch = "x86_64")]`
- `crates/fff-core/src/bigram_filter.rs:604` — NEON dispatch `#[cfg(all(target_arch = "aarch64", target_feature = "neon"))]`
- `crates/fff-core/src/bigram_filter.rs:623` — `normalize_bytes_avx2` `#[cfg(target_arch = "x86_64")]`
- `crates/fff-core/src/bigram_filter.rs:656` — `normalize_bytes_neon` `#[cfg(all(target_arch = "aarch64", target_feature = "neon"))]`
- `crates/fff-core/src/case_insensitive_memmem.rs:106,375` — `verify_avx2`, `search_packed_pair_avx2` `#[cfg(target_arch = "x86_64")]`
- `crates/fff-core/src/case_insensitive_memmem.rs:171,197,255` — NEON helpers `#[cfg(target_arch = "aarch64")]`
- `crates/fff-core/src/case_insensitive_memmem.rs:353,359,505,516` — runtime dispatch gated by arch
- `crates/fff-core/src/case_insensitive_memmem.rs:499` — `select_rare_pair` result `#[cfg_attr(not(any(target_arch = "x86_64", target_arch = "aarch64")), allow(unused_variables))]`

On i686 all SIMD paths compile out; `normalize_bytes_scalar` / `search` (memchr2 fallback) run and LLVM auto-vectorises them with the baseline SIMD. No further code was failing to compile.

If you were seeing a stale failure in your local view, please point me at the specific error — otherwise ready for review.

Honk-Honk 🪿
